### ISSUE TITLE
King County COVID19 - Bug: Escape key should close the chatbot window

### ISSUE THREAD

**Issue by alboss** [a11ySea/testing#21]
## Issue Summary

The escape key on the keyboard does not close the chatbot window

## Steps to reproduce

1. Go to [https://kingcounty.gov/depts/health/covid-19.aspx](https://kingcounty.gov/depts/health/covid-19.aspx)
2. Click on _COVID-19 Questions?_
3. Try to close the pop-up by using the _ESC_ key on the keyboard
4. Nothing happens

### Expected behavior

- Clippy goes away

### Actual behavior

- Clippy doesn't go away

### Device Information:

 - OS: Mac OS X, but I'd expect the same in Windows or Linux 
 - Browser: Firefox, but I'd expect the same in any desktop browser

### Suggested Code

Probably something like this:

```
window.addEventListener('keydown', function (event) {
  if (event.key === 'Escape') {
    chatFrame.style.visibility = 'hidden';
  }
})
```

# Specifications

- **[WCAG Principal 2: Operable](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#operable) - User interface components and navigation must be operable.**
- **[WCAG SC: Guideline 2.1 Keyboard Accessible](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html): Make all functionality available from a keyboard.**
- **Severity: required for minimum (Level A) compliance**

**Comment by dereksheppard** [comment]
@alboss I published the change and added it to my repo.

**Comment by alboss** [comment]
Fixed; thank you!
